backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img
# media_library:
#   name: uploadcare
#   config:
#     publicKey: 4c411270a33525bd99c5

collections:
  - name: "お知らせ"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime" }
      - { label: "概要", name: "description", widget: "text" }
      - {
          label: "注目記事",
          name: "featuredpost",
          widget: "boolean",
          default: false,
        }
      - {
          label: "アイキャッチ画像",
          name: "featuredimage",
          widget: image,
          required: false,
        }
      - { label: "内容", name: "body", widget: "markdown" }
      - { label: "タグ", name: "tags", widget: "list", required: false }

  - name: "ページ"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "トップページ"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: タイトル, name: title, widget: string }
          - { label: 画像, name: image, widget: image }
          - { label: スライドショー画像, name: photos, widget: list }
          - {
              label: 見出し文,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: タイトル, name: title, widget: string },
                  { label: 内容, name: description, widget: text },
                ],
            }
          - { label: 見出し, name: heading, widget: string }
          - { label: 説明文, name: description, widget: string }
          - {
              label: 特徴の説明,
              name: intro,
              widget: list,
              fields:
                [
                  { label: タイトル, name: name, widget: string },
                  { label: 内容, name: text, widget: text },
                  { label: 画像, name: image, widget: image },
                ],
            }
      - file: "src/pages/pricing/index.md"
        label: "料金"
        name: "pricing"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "pricing-page",
            }
          - { label: 画像, name: image, widget: image }
          - { label: タイトル, name: title, widget: string }
          - { label: 料金表説明, name: description, widget: text }
          - {
              label: 料金表,
              name: servicePricing,
              widget: list,
              fields:
                [
                  { label: コース名, name: name, widget: string },
                  { label: 個室席（税抜）, name: boothPrice, widget: string },
                  {
                    label: 個室席（税込）,
                    name: boothPriceTax,
                    widget: string,
                  },
                  {
                    label: オープン席（税抜）,
                    name: openPrice,
                    widget: string,
                  },
                  {
                    label: オープン席（税込）,
                    name: openPriceTax,
                    widget: string,
                  },
                ],
            }
          - {
              label: シャワー料金表,
              name: showerPricing,
              widget: list,
              fields:
                [
                  { label: 名前, name: name, widget: string },
                  { label: 料金, name: price, widget: string },
                ],
            }
          - { label: シャワー説明, name: showerDescription, widget: text }
      - file: "src/pages/floor/index.md"
        label: "席・ブース"
        name: "floor"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "floor-page",
            }
          - { label: 画像, name: image, widget: image }
          - { label: タイトル, name: title, widget: string }
          - { label: 説明文, name: description, widget: text }
          - { label: 店内マップ, name: floorMapImage, widget: image }
          - {
              label: 席情報,
              name: seats,
              widget: list,
              fields:
                [
                  { label: 席名, name: name, widget: string },
                  { label: 説明文, name: text, widget: text },
                  { label: 画像, name: image, widget: image },
                ],
            }
          - {
              label: 設備情報,
              name: facility,
              widget: list,
              fields:
                [
                  { label: 設備名, name: name, widget: string },
                  { label: 説明文, name: text, widget: text },
                  { label: 画像, name: image, widget: image },
                ],
            }
      - file: "src/pages/search/index.md"
        label: "コミック検索"
        name: "search"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "search-page",
            }
          - { label: 画像, name: image, widget: image }
          - { label: タイトル, name: title, widget: string }
          - { label: 説明文, name: description, widget: text }
          - { label: フロアマップ, name: floorMapImage, widget: image }
          - { label: 雑誌情報, name: magazines, widget: text }
      - file: "src/pages/access/index.md"
        label: "アクセス"
        name: "access"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "access-page",
            }
          - { label: 画像, name: image, widget: image }
          - { label: タイトル, name: title, widget: string }
          - { label: 説明文, name: description, widget: text }
          - { label: 参考写真, name: accessImage, widget: image }
      - file: "src/pages/recruit/index.md"
        label: "アルバイト募集"
        name: "recruit"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "recruit-page",
            }
          - { label: 画像, name: image, widget: image }
          - { label: タイトル, name: title, widget: string }
          - { label: 説明文, name: description, widget: text }
